SELECT
    DATE_TRUNC('day', END_TIME) AS "Day",
    SUM(EXECUTION_TIME) / 1000 / 60 / 60 AS "Compute Hours",
    SUM(BYTES_SCANNED) / 1024 / 1024 / 1024 AS "Data Scanned (GB)"
FROM
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
    QUERY_TYPE = 'SELECT'
    AND END_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY
    "Day"
ORDER BY
    "Day" ASC;
