SELECT
    DATE_TRUNC('day', LAST_LOAD_TIME) as "Day",
    TABLE_CATALOG_NAME,
    TABLE_SCHEMA_NAME,
    TABLE_NAME,
    SUM(ROW_COUNT) as "Row Count",
    SUM(FILE_SIZE) /1024 / 1024 as "File Size (MB)",
    SUM(ERROR_COUNT) as "Error Count"
FROM
    SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
GROUP BY
"Day", TABLE_CATALOG_NAME, TABLE_SCHEMA_NAME, TABLE_NAME
ORDER BY
    "File Size (MB)" DESC;
