SELECT
    TABLE_CATALOG_NAME,
    TABLE_SCHEMA_NAME,
    TABLE_NAME,
    DATE_TRUNC('day', LAST_LOAD_TIME) AS "Day",
    SUM(ROW_COUNT) AS "Row Count",
    SUM(FILE_SIZE) / 1024 / 1024 AS "File Size (MB)",
    SUM(ERROR_COUNT) AS "Error Count"
FROM
    SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
GROUP BY
    "Day", TABLE_CATALOG_NAME, TABLE_SCHEMA_NAME, TABLE_NAME
ORDER BY
    "File Size (MB)" DESC;
